### ISSUE TITLE
Use a turtle form for config instead of JSON?

### ISSUE THREAD

**Issue by timbl** [jeff-zucker/data-kitchen#3]
and  then use the solid-ui form system to edit it?

**Comment by jeff-zucker** [comment]
Yes, for sure in the future.  We need some of the config in JSON because it loads in the main process before we have access to rdlib, but most of it can be handled later.

**Comment by jeff-zucker** [comment]
This is implemented now - the config is in Turtle and there is an automatically generated solid-ui form to edit it.  I restyled the editing form for single-page use and also wrote a generic RDF-config handler.  And modified rdflib's updater in mashlib to use solid-rest for local file updating.
