### ISSUE TITLE
In rest.js use encodeURI for filenames in turtle representation

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/data-kitchen#4]
Actually filenames with unencoded spaces are just not considered in `container2turtle`
To avoid that I tested the NSS solution to encodeURI() : 
- comment out L155
- L159 : `let fn = encodeURI(filenames[i])`
- L205 : `let fn = encodeURI(pathname.replace(/.*\//,''));`

NSS and databrowser are taken care of decodeURI()

**Comment by jeff-zucker** [comment]
Thanks, done and committed in the data-kitchen bundles repo, not yet in the solid-rest repo ... I need to test the many changes I made in the data-kitcehen bundles repo before putting them back into the main solid-rest repo.
