### ISSUE TITLE
filemanager : using + in destination filename error 500 and create a folder

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/data-kitchen#6]
`SFCFetchError. SFCFectchError 500 .... An internal server error occured`

was copying : 
- from : `filename%20with%20spaces.txt`
- to: `filename+with spaces.txt`

a folder naned `filename+with spaces.txt` is created

**Comment by jeff-zucker** [comment]
Was this on NSS or a local file?  Why are you filing this in data-kitchen rather than Solid-File-Client or Solid-Rest?

**Comment by bourgeoa** [comment]
It was on local file with data-kitchen.

**Comment by jeff-zucker** [comment]
But Data Kitchen doesn't have anything to do with it.  It simply passes it along to Solid-File-Client which passes it to Solid-Rest.

**Comment by bourgeoa** [comment]
I did not notice the `solid-rest` error before : 

> C:\Users\alain\github\jeff-zucker\data-kitchen\bundles\solid-rest\src\file.js:93 Error: EISDIR: illegal operation on a directory, open 'C:\Users\alain\github\jeff-zucker\data-kitchen\myPod\public\filename+with spaces.txt'

**Comment by jeff-zucker** [comment]
Yes I guess it is in the data-kitchen rest so this is the right place to put the issue ... testing now, I got the same thing - rest thinks it is a folder.

**Comment by jeff-zucker** [comment]
Okay, found it, the code for recursively creating containers was mistaking the file as a container.  Apparently the bug has been there all along.  Fixed and committed.

**Comment by jeff-zucker** [comment]
Maybe we never tried with a filename with a plus in it previously.  At any rate, I believe it is solved now.
