### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by scenaristeur** [jeff-zucker/data-kitchen#8]
Hi @jeff-zucker 
link to Windows is broken on this page https://jeff-zucker.github.io/data-kitchen.html

**Comment by jeff-zucker** [comment]
Should be fixed now.  There are some issues with the Windows version.  I'm recovering from surgery so may be away from keyboard sometimes but will still appreciate feedback.  Thanks for all the great work you do.

**Comment by scenaristeur** [comment]
link is ok, i 'll test it. Great work is decentralized. Each of us got a part ;-)
